### ISSUE TITLE
[Cardputer] Startup sound on Cardputer from M5 demo

### ISSUE THREAD

**Issue by valentin8709** [valentin8709/bruce-extended#15]
See boot sound : https://github.com/m5stack/M5Cardputer-UserDemo/blob/main/main/apps/utils/boot_sound/boot_sound_1.h

Called from : https://github.com/m5stack/M5Cardputer-UserDemo/blob/7d99ee484439b36a172a3e2b68394a13dcdcd88f/main/apps/launcher/port/port.cpp#L13

**Comment by valentin8709** [comment]
Done by @bmorcelli in 76bc410b3dc830977906180d62f00f9dee89750c

**Comment by bmorcelli** [comment]
?
